services:
  bot:
    # image: sir_5rm9_bot:latest
    image: ghcr.io/magurouhiru/sir-5rm9_bot:20260327
    environment:
      - DEV_MODE=on
      - with_ocr_server=on
      - with_gcp_token=off
      - ocr_server_path=http://ocr
    secrets:
      - DISCORD_TOKEN
  ocr:
    # image: sir_5rm9_ocr:latest
    image: ghcr.io/magurouhiru/sir-5rm9_ocr:20260327
    ports:
      - "8000:80"

secrets:
  DISCORD_TOKEN:
    file: ./discord_token.txt
