services:
  app:
    image: sir_5rm9:latest
    environment:
      - APP_ENV=production
    secrets:
      - DISCORD_TOKEN
#   ollama:
#     image: ollama/ollama:latest
#     ports:
#       - "11434:11434"
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: all # すべてのGPUを指定
#               capabilities: [ gpu ] # 必須設定
#     volumes:
#       - ollama_data:/root/.ollama

# volumes:
#   ollama_data:

secrets:
  DISCORD_TOKEN:
    file: ./discord_token.txt
