services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - DEV_MODE=true
      - WITH_GCP_TOKEN=false
      - OCR_SERVER_PATH=http://localhost:8000
    secrets:
      - DISCORD_TOKEN
    volumes:
      - ..:/home/vscode/app

secrets:
  DISCORD_TOKEN:
    file: ../discord_token.txt
