name: cicd

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        pipx install uv
        uv sync --no-dev
        pip install ruff
    - name: Analysing the code with ruff
      run: |
        uv run ruff check --output-format=github
        uv run ruff format --check --output-format=github

  build:
    runs-on: ubuntu-latest
    needs: check
    # if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/sir_5rm9:latest .
        docker push ghcr.io/${{ github.repository }}/sir_5rm9:latest
