name: ci

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        pipx install uv
        uv sync --no-dev
        pip install ruff
    - name: Analysing the code with ruff
      run: |
        ruff check --output-format=github
        ruff format --check --output-format=github
